source ~/.bashrc

alias reload_setup="(z dotfiles && ./setup.sh && cd ~)"
source ~/.z.sh
source ~/.work_related.sh
source ~/.pretty_prompt.sh
source ~/.directory_structure.sh
source ~/.util.sh
source ~/.java_specific.sh

#source ~/.osx_install_apps.sh
#source ~/.osx_pretty.sh

alias g=git

export NVM_DIR=~/.nvm
  source $(brew --prefix nvm)/nvm.sh

export PATH=/usr/local/sbin:$PATH
