
PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

alias ls="ls -G"
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcxy


PERL_MB_OPT="--install_base \"/Users/test/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/Users/test/perl5"; export PERL_MM_OPT;
