tap 'homebrew/bundle'
tap 'homebrew/dupes'
tap 'homebrew/versions'

brew 'the_silver_searcher'

#update
#upgrade

tap 'caskroom/cask'
tap 'caskroom/versions'

cask 'google-chrome'
cask 'firefox'

cask 'sublime-text'

cask 'java'
cask 'java7'
cask 'java6'

cask 'evernote'
